name: CloudFormation Guard Analysis

on:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  guard:
    permissions:
      security-events: write
    runs-on: ubuntu-latest
    name: CloudFormation Guard Analyze
    steps:
      - name: CloudFormation Guard Analyze
        uses: aws-cloudformation/cloudformation-guard@action-v0.0.3
        with:
          rules: 'resources/validate/rules'
          data: 'resources/validate/data'
          analyze: true