name: CloudFormation Guard Analysis

on: workflow_dispatch

jobs:
  guard:
    permissions:
      security-events: write
    runs-on: macos-latest
    name: CloudFormation Guard Analyze
    steps:
      - name: CloudFormation Guard Analyze
        uses: aws-cloudformation/cloudformation-guard@action-v0.0.3
        with:
          rules: 'resources/validate/rules'
          data: 'resources/validate/data'
          analyze: true